name: Check Steam Games Updates

on:
  # Run daily at 9:00 AM UTC
  schedule:
    - cron: '0 9 * * *'

  # Allow manual trigger
  workflow_dispatch:

  # Run on push to main for testing
  push:
    branches:
      - master
    paths:
      - 'games.txt'
      - 'check_updates.py'
      - 'steam_build_tracker.py'
      - '.github/workflows/check_updates.yml'

jobs:
  check-updates:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install SteamCMD
        run: |
          sudo add-apt-repository multiverse -y
          sudo dpkg --add-architecture i386
          sudo apt-get update
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          sudo apt-get install -y lib32gcc-s1 steamcmd
          # Verify installation
          which steamcmd || echo "SteamCMD not found in PATH"

      - name: Check for game updates
        id: check
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        run: |
          python check_updates.py
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Configure Git
        if: steps.check.outputs.exit_code == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: steps.check.outputs.exit_code == '1'
        run: |
          git add tracked_games.json
          git commit -m "Update tracked games data - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push

      - name: Summary
        run: |
          if [ "${{ steps.check.outputs.exit_code }}" == "1" ]; then
            echo "Updates detected and committed!"
          else
            echo "No updates detected."
          fi
